### PR TITLE
Auto close functionality

### PR DESCRIPTION
**Pull request by anush-cr**
added two new classes: auto-close, auto-close-on-empty
auto-close: The input is shrunk automatically when it loses focuses.
auto-close-on-empty: Prevents shrinking of input if text is entered in the input.
[example](https://jsfiddle.net/24whhxt7/1/)

### CODE REVIEW

**Comment by sconstantinides** [comment]
This is awesome!

One small issue: Button-2 in your example isn't exactly the same width in both states (in Chrome or Firefox).

**Comment by anush-cr** [comment]
The tidy up function on JSFiddle was introducing some unnecessary  whitespace at the closing tag of the label,thus increasing it's width by around 4px. 
It works fine now without tidying up the code. [updated example](https://jsfiddle.net/24whhxt7/3/)
There is a ~0.5px increase always from rounding off calculations of input width.

**Comment by sconstantinides** [comment]
Cool. Something else I just noticed: what's the reason for setting tab-index to -1?

**Comment by anush-cr** [comment]
I had added it to shift focus when many form-buttons are active, but it does so without it as well. I'll go ahead and remove it.

**Comment by sconstantinides** [comment]
Thanks again!

**Pull request merged**
